# Generated by Django 6.0.4 on 2026-05-16 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(choices=[('fire', 'Fire'), ('flood', 'Flood'), ('earthquake', 'Earthquake'), ('medical', 'Medical'), ('structural', 'Structural Collapse'), ('other', 'Other')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('dos', models.TextField(help_text='One do per line')),
                ('donts', models.TextField(help_text="One don't per line")),
                ('extra_info', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'authority'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
