# Generated by Django 6.0.5 on 2026-05-16 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AidStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lives_saved', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'authority'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aid Stats',
            },
        ),
        migrations.CreateModel(
            name='CashDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('bkash_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'authority'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('goods_name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('delivery_method', models.CharField(choices=[('dropoff', 'Drop-off at Office'), ('pickup', 'Request Pickup')], max_length=10)),
                ('pickup_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Pickup Scheduled'), ('received', 'Received')], default='pending', max_length=10)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, limit_choices_to={'role': 'volunteer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
